version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Aevum176942
      MYSQL_USER: root2
      MYSQL_PASSWORD: Aevum176942
      MYSQL_DATABASE: db_example

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_example
      SPRING_DATASOURCE_USERNAME: root2
      SPRING_DATASOURCE_PASSWORD: Aevum176942

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"